unit clsResources;

interface

type

  repositoryResources = class
  public
    const

    //sections
    RESOURCES_SECTION              = 'RESOURCES';


    //names
    LOADING_RESOURCE               = 'LOADING';

    MSG_BOX_INFO_ICON_RESOURCE     = 'MSG_BOX_INFO_ICON';
    MSG_BOX_QUESTION_RESOURCE      = 'MSG_BOX_QUESTION_ICON';
    MSG_BOX_WARNING_RESOURCE       = 'MSG_BOX_WARNING_ICON';
    MSG_BOX_CRITICAL_RESOURCE      = 'MSG_BOX_CRITICAL_ICON';

    TABLE_PAGER_FIRST_RESOURCE     = 'TABLE_PAGER_FIRST_ICON';
    TABLE_PAGER_PREV_RESOURCE      = 'TABLE_PAGER_PREV_ICON';
    TABLE_PAGER_NEXT_RESOURCE      = 'TABLE_PAGER_NEXT_ICON';
    TABLE_PAGER_LAST_RESOURCE      = 'TABLE_PAGER_LAST_ICON';

    WINCONTROL_LOCK_DECORATOR_LOCK_RESOURCE      = 'WINCONTROL_LOCK_DECORATOR_LOCK';
  end;

implementation

end.
